$(document).ready(function(){
    $(".J_selectTime").datepicker({
        autoSize:true,
        dateFormat:"yy-mm-dd",
        dayNamesMin:["日","一","二","三","四","五","六"],
        monthNamesShort:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
        changeMonth:true,
        changeYear:true,
        showAnim:"fadeIn",
        showMonthAfterYear:true,
    });
});
